

services:
  worker0:    
    build: .
    container_name: worker0
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - TF_CONFIG={"cluster":{"worker":["localhost:12345","localhost:12346"]},"task":{"type":"worker","index":0}}
    command: ["python", "train_with_hadoop.py"]
    network_mode: host

  worker1:
    build: .
    container_name: worker1
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - TF_CONFIG={"cluster":{"worker":["localhost:12345","localhost:12346"]},"task":{"type":"worker","index":1}}
    command: ["python", "train_with_hadoop.py"]
    network_mode: host
