services:
  worker0:    
    build: .
    container_name: worker0
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - TF_CONFIG={"cluster":{"worker":["worker0:12345","worker1:12345"]},"task":{"type":"worker","index":0}}
    command: ["python", "train_with_hadoop.py"]
    networks:
      - hadoop_net

  worker1:
    build: .
    container_name: worker1
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - TF_CONFIG={"cluster":{"worker":["worker0:12345","worker1:12345"]},"task":{"type":"worker","index":1}}
    command: ["python", "train_with_hadoop.py"]
    networks:
      - hadoop_net

networks:
  hadoop_net:
    external: true
